/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arsene' at '26/11/16 18:35' with Gradle 3.0
 *
 * @author Arsene, @date 26/11/16 18:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
